
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: elastic-stack
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |    
    input 
    {
      beats 
      {
        port => 5044
        host => "0.0.0.0"
      }
    }
    filter 
    {
      grok 
      {
        match => [ "message" , "%{COMBINEDAPACHELOG}+%{GREEDYDATA:extra_fields}"]
        overwrite => [ "message" ]
      }
      mutate 
      {
        convert => ["response", "integer"]
        convert => ["bytes", "integer"]
        convert => ["responsetime", "float"]
      }
      geoip 
      {
        source => "clientip"
        target => "geoip"
        add_tag => [ "nginx-geoip" ]
      }
      date 
      {
        match => [ "timestamp" , "dd/MMM/YYYY:HH:mm:ss Z" ]
        remove_field => [ "timestamp" ]
      }
      useragent 
      {
        source => "agent"
      }
    }
    output 
    {
      elasticsearch 
      {
        hosts => [ "${ES_HOSTS}" ]
        user => "${ELASTIC_USER}"
        password => "${ELASTIC_PASSWORD}"  
        #index => "logstash-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elastic-stack
spec:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec: 
      containers:
      - image: docker.elastic.co/logstash/logstash:7.17.9
        imagePullPolicy: IfNotPresent
        name: logstash
        ports:
        - containerPort: 25826
        - containerPort: 5044
        env:
        - name: ES_HOSTS
          value: "http://elasticsearch.elastic-stack:9200"
        - name: ELASTIC_USER
          valueFrom:
            secretKeyRef:
              name: elastic-secret
              key: ELASTIC_USERNAME
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-secret
              key: ELASTIC_PASSWORD
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 1Gi
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/logstash/config
        - name: logstash-pipeline-volume
          mountPath: /usr/share/logstash/pipeline  
      volumes:
      - name: config-volume
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.conf
              path: logstash.conf
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash-service
  namespace: elastic-stack
spec:
  ports:
  - name: "25826"
    port: 25826
    targetPort: 25826
  - name: "5044"
    port: 5044
    targetPort: 5044
  selector:
    app: logstash
---